// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: smartcity.proto

package smartcity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrafficRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoadId        string                 `protobuf:"bytes,1,opt,name=road_id,json=roadId,proto3" json:"road_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficRequest) Reset() {
	*x = TrafficRequest{}
	mi := &file_smartcity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficRequest) ProtoMessage() {}

func (x *TrafficRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficRequest.ProtoReflect.Descriptor instead.
func (*TrafficRequest) Descriptor() ([]byte, []int) {
	return file_smartcity_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficRequest) GetRoadId() string {
	if x != nil {
		return x.RoadId
	}
	return ""
}

type TrafficStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoadId          string                 `protobuf:"bytes,1,opt,name=road_id,json=roadId,proto3" json:"road_id,omitempty"`
	CongestionLevel string                 `protobuf:"bytes,2,opt,name=congestion_level,json=congestionLevel,proto3" json:"congestion_level,omitempty"`
	VehicleCount    int32                  `protobuf:"varint,3,opt,name=vehicle_count,json=vehicleCount,proto3" json:"vehicle_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrafficStatus) Reset() {
	*x = TrafficStatus{}
	mi := &file_smartcity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficStatus) ProtoMessage() {}

func (x *TrafficStatus) ProtoReflect() protoreflect.Message {
	mi := &file_smartcity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficStatus.ProtoReflect.Descriptor instead.
func (*TrafficStatus) Descriptor() ([]byte, []int) {
	return file_smartcity_proto_rawDescGZIP(), []int{1}
}

func (x *TrafficStatus) GetRoadId() string {
	if x != nil {
		return x.RoadId
	}
	return ""
}

func (x *TrafficStatus) GetCongestionLevel() string {
	if x != nil {
		return x.CongestionLevel
	}
	return ""
}

func (x *TrafficStatus) GetVehicleCount() int32 {
	if x != nil {
		return x.VehicleCount
	}
	return 0
}

type AirQualityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AirQualityRequest) Reset() {
	*x = AirQualityRequest{}
	mi := &file_smartcity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirQualityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirQualityRequest) ProtoMessage() {}

func (x *AirQualityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirQualityRequest.ProtoReflect.Descriptor instead.
func (*AirQualityRequest) Descriptor() ([]byte, []int) {
	return file_smartcity_proto_rawDescGZIP(), []int{2}
}

func (x *AirQualityRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

type AirQualityData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZoneId         string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	PollutionLevel float32                `protobuf:"fixed32,2,opt,name=pollution_level,json=pollutionLevel,proto3" json:"pollution_level,omitempty"`
	Timestamp      string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AirQualityData) Reset() {
	*x = AirQualityData{}
	mi := &file_smartcity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirQualityData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirQualityData) ProtoMessage() {}

func (x *AirQualityData) ProtoReflect() protoreflect.Message {
	mi := &file_smartcity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirQualityData.ProtoReflect.Descriptor instead.
func (*AirQualityData) Descriptor() ([]byte, []int) {
	return file_smartcity_proto_rawDescGZIP(), []int{3}
}

func (x *AirQualityData) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *AirQualityData) GetPollutionLevel() float32 {
	if x != nil {
		return x.PollutionLevel
	}
	return 0
}

func (x *AirQualityData) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type TrafficLightCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IntersectionId string                 `protobuf:"bytes,1,opt,name=intersection_id,json=intersectionId,proto3" json:"intersection_id,omitempty"`
	Action         string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrafficLightCommand) Reset() {
	*x = TrafficLightCommand{}
	mi := &file_smartcity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficLightCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficLightCommand) ProtoMessage() {}

func (x *TrafficLightCommand) ProtoReflect() protoreflect.Message {
	mi := &file_smartcity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficLightCommand.ProtoReflect.Descriptor instead.
func (*TrafficLightCommand) Descriptor() ([]byte, []int) {
	return file_smartcity_proto_rawDescGZIP(), []int{4}
}

func (x *TrafficLightCommand) GetIntersectionId() string {
	if x != nil {
		return x.IntersectionId
	}
	return ""
}

func (x *TrafficLightCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_smartcity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smartcity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_smartcity_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EmergencyCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        string                 `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergencyCommand) Reset() {
	*x = EmergencyCommand{}
	mi := &file_smartcity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergencyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergencyCommand) ProtoMessage() {}

func (x *EmergencyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_smartcity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergencyCommand.ProtoReflect.Descriptor instead.
func (*EmergencyCommand) Descriptor() ([]byte, []int) {
	return file_smartcity_proto_rawDescGZIP(), []int{6}
}

func (x *EmergencyCommand) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *EmergencyCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type EmergencyFeedback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        string                 `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergencyFeedback) Reset() {
	*x = EmergencyFeedback{}
	mi := &file_smartcity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergencyFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergencyFeedback) ProtoMessage() {}

func (x *EmergencyFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_smartcity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergencyFeedback.ProtoReflect.Descriptor instead.
func (*EmergencyFeedback) Descriptor() ([]byte, []int) {
	return file_smartcity_proto_rawDescGZIP(), []int{7}
}

func (x *EmergencyFeedback) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *EmergencyFeedback) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EmergencyFeedback) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

var File_smartcity_proto protoreflect.FileDescriptor

const file_smartcity_proto_rawDesc = "" +
	"\n" +
	"\x0fsmartcity.proto\x12\tsmartcity\")\n" +
	"\x0eTrafficRequest\x12\x17\n" +
	"\aroad_id\x18\x01 \x01(\tR\x06roadId\"x\n" +
	"\rTrafficStatus\x12\x17\n" +
	"\aroad_id\x18\x01 \x01(\tR\x06roadId\x12)\n" +
	"\x10congestion_level\x18\x02 \x01(\tR\x0fcongestionLevel\x12#\n" +
	"\rvehicle_count\x18\x03 \x01(\x05R\fvehicleCount\",\n" +
	"\x11AirQualityRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\"p\n" +
	"\x0eAirQualityData\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12'\n" +
	"\x0fpollution_level\x18\x02 \x01(\x02R\x0epollutionLevel\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"V\n" +
	"\x13TrafficLightCommand\x12'\n" +
	"\x0fintersection_id\x18\x01 \x01(\tR\x0eintersectionId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"+\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"E\n" +
	"\x10EmergencyCommand\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\tR\x06unitId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"`\n" +
	"\x11EmergencyFeedback\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\tR\x06unitId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation2\xcf\x02\n" +
	"\x10SmartCityService\x12G\n" +
	"\x10GetTrafficStatus\x12\x19.smartcity.TrafficRequest\x1a\x18.smartcity.TrafficStatus\x12M\n" +
	"\x10StreamAirQuality\x12\x1c.smartcity.AirQualityRequest\x1a\x19.smartcity.AirQualityData0\x01\x12P\n" +
	"\x10SetTrafficLights\x12\x1e.smartcity.TrafficLightCommand\x1a\x1a.smartcity.CommandResponse(\x01\x12Q\n" +
	"\x10EmergencyControl\x12\x1b.smartcity.EmergencyCommand\x1a\x1c.smartcity.EmergencyFeedback(\x010\x01B\x15Z\x13smartcity/smartcityb\x06proto3"

var (
	file_smartcity_proto_rawDescOnce sync.Once
	file_smartcity_proto_rawDescData []byte
)

func file_smartcity_proto_rawDescGZIP() []byte {
	file_smartcity_proto_rawDescOnce.Do(func() {
		file_smartcity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smartcity_proto_rawDesc), len(file_smartcity_proto_rawDesc)))
	})
	return file_smartcity_proto_rawDescData
}

var file_smartcity_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_smartcity_proto_goTypes = []any{
	(*TrafficRequest)(nil),      // 0: smartcity.TrafficRequest
	(*TrafficStatus)(nil),       // 1: smartcity.TrafficStatus
	(*AirQualityRequest)(nil),   // 2: smartcity.AirQualityRequest
	(*AirQualityData)(nil),      // 3: smartcity.AirQualityData
	(*TrafficLightCommand)(nil), // 4: smartcity.TrafficLightCommand
	(*CommandResponse)(nil),     // 5: smartcity.CommandResponse
	(*EmergencyCommand)(nil),    // 6: smartcity.EmergencyCommand
	(*EmergencyFeedback)(nil),   // 7: smartcity.EmergencyFeedback
}
var file_smartcity_proto_depIdxs = []int32{
	0, // 0: smartcity.SmartCityService.GetTrafficStatus:input_type -> smartcity.TrafficRequest
	2, // 1: smartcity.SmartCityService.StreamAirQuality:input_type -> smartcity.AirQualityRequest
	4, // 2: smartcity.SmartCityService.SetTrafficLights:input_type -> smartcity.TrafficLightCommand
	6, // 3: smartcity.SmartCityService.EmergencyControl:input_type -> smartcity.EmergencyCommand
	1, // 4: smartcity.SmartCityService.GetTrafficStatus:output_type -> smartcity.TrafficStatus
	3, // 5: smartcity.SmartCityService.StreamAirQuality:output_type -> smartcity.AirQualityData
	5, // 6: smartcity.SmartCityService.SetTrafficLights:output_type -> smartcity.CommandResponse
	7, // 7: smartcity.SmartCityService.EmergencyControl:output_type -> smartcity.EmergencyFeedback
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smartcity_proto_init() }
func file_smartcity_proto_init() {
	if File_smartcity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smartcity_proto_rawDesc), len(file_smartcity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smartcity_proto_goTypes,
		DependencyIndexes: file_smartcity_proto_depIdxs,
		MessageInfos:      file_smartcity_proto_msgTypes,
	}.Build()
	File_smartcity_proto = out.File
	file_smartcity_proto_goTypes = nil
	file_smartcity_proto_depIdxs = nil
}
